/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema.de.facturacion;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
public class BuscarProveedores extends javax.swing.JFrame {

    /**
     * Creates new form BuscarProveedores
     */
    DefaultTableModel modelo;
    public BuscarProveedores() {
        initComponents();
        cargartablapro("");
        
    }
public void cargartablapro(String dato)
    {
        String[] titulos = {"CEDULA", "NOMBRE", "APELLIDO","CODIGO EMPRESA","CELULAR","REPRESENTANTE","EXTENSION"};
        String[] registros = new String[7];
        modelo = new DefaultTableModel(null, titulos);
        TblPro.setModel(modelo);
        conexion_mysql cc = new conexion_mysql();
        Connection cn = cc.conectar();
        String sql = "";
        sql = "select * from proveedores where CED_PROV LIKE'%" + dato + "%' or APE_PRO LIKE'%" +dato+"%' order by APE_PRO";
        try {
            Statement psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("CED_PROV");
                registros[1] = rs.getString("NOM_PRO");
                registros[2] = rs.getString("APE_PRO");
                registros[3] = rs.getString("COD_EMP_PRO");
                registros[4] = rs.getString("CEL_PROV");
                registros[5] = rs.getString("REP_LEG_PROV");
                registros[6] = rs.getString("EXT1_PROV");
                
                modelo.addRow(registros);

            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
     public void cargarcampos()
    {
        Proveedor prov = new Proveedor();
        conexion_mysql cc = new conexion_mysql();
        Connection cn = cc.conectar();
        String sql = "";
        int fila = TblPro.getSelectedRow();
        String ced=TblPro.getValueAt(fila, 0).toString().trim();
                        
        sql = "select * from proveedores where CED_PROV= '"+ced+"'";
        try {
            Statement psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sql);
            while (rs.next()) {
                prov.txtCed.setText(ced);
                rs.getString("CED_PROV");
                rs.getString("NOM_PRO");
                rs.getString("APE_PRO");
                rs.getString("COD_EMP_PRO");
                rs.getString("CEL_PROV");
                rs.getString("REP_LEG_PROV");
                rs.getString("EXT1_PROV");
                }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }
public void bloquear()
    {
        Proveedor pro = new Proveedor();
                    pro.txtCed.setEnabled(false);
                    pro.TxtNombre.setEnabled(false);
                    pro.TxtApellido.setEnabled(false);
                    pro.txtRUC.setEnabled(false);
                    pro.CbxCodigoEmpresa.setEnabled(false);
                    pro.cbxProv.setEnabled(false);
                    pro.cbxCan.setEnabled(false);
                    pro.txtTelfCelu.setEnabled(false);
                    pro.txtTelfComve.setEnabled(false);
                    pro.txtEmail.setEnabled(false);
                    pro.txtRzon.setEnabled(false);
                    pro.txtReLe.setEnabled(false);
                    pro.txtExt1.setEnabled(false);
    }
    public void mayusclemail(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if(Character.isLowerCase(c))
        {
            String cad=(""+c).toUpperCase();
            c=cad.charAt(0);
            evt.setKeyChar(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBuscarKeyTyped(evt);
            }
        });

        jButton1.setText("SELECCIONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        TblPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TblPro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarKeyReleased
        cargartablapro(TxtBuscar.getText());
    }//GEN-LAST:event_TxtBuscarKeyReleased

    private void TxtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarKeyTyped
        
        mayusclemail(evt);
         if(TxtBuscar.getText().length() >9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TxtBuscarKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Proveedor prov = new Proveedor();
        conexion_mysql cc = new conexion_mysql();
        Connection cn = cc.conectar();
        String sql = "";
        int fila = TblPro.getSelectedRow();
        String ced=TblPro.getValueAt(fila, 0).toString().trim();
                        
        sql = "select * from proveedores where CED_PROV= '"+ced+"'";
        try {
            Statement psd = cn.createStatement();
            ResultSet rs = psd.executeQuery(sql);
            while (rs.next()) {
                prov.txtCed.setText(rs.getString("CED_PROV"));
                prov.TxtNombre.setText(rs.getString("NOM_PRO"));
                prov.TxtApellido.setText(rs.getString("APE_PRO"));
                prov.txtRUC.setText(rs.getString("RUC_PROV"));
                prov.CbxCodigoEmpresa.setSelectedItem(rs.getString("COD_EMP_PRO"));
                prov.txtTelfCelu.setText(rs.getString("CEL_PROV"));
                prov.txtTelfComve.setText(rs.getString("TLF1_PROV"));
                prov.txtRzon.setText(rs.getString("FOR_PAG_PROV"));
                prov.txtEmail.setText(rs.getString("E_MAIL_PROV"));
                prov.CbxCodigoEmpresa.setSelectedItem(rs.getString("CEL_PROV"));
                prov.cbxProv.setSelectedItem(rs.getString("PRO_PROV"));
                prov.cbxCan.setSelectedItem(rs.getString("CANT_PROV"));
                prov.txtReLe.setText(rs.getString("REP_LEG_PROV"));
                prov.txtExt1.setText(rs.getString("EXT1_PROV"));
                
                }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
//cargarcampos();
        prov.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Proveedor pro = new Proveedor();
        pro.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblPro;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
