/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dialogs;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import sistema.de.facturacion.conexion_mysql;

/**
 *
 * @author Benjita
 */
public class busquedaFactura extends javax.swing.JDialog {

    /**
     * Creates new form busquedaFactura
     */
    public busquedaFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        buscarSecuencial();
        busqueda(" ");
        seleccionar();
    }
    DefaultTableModel modelo;
    public  String numero="";
    public String cliente="";
    public void seleccionar(){
        jtblFacturas.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                int index=jtblFacturas.getSelectedRow();
               // if(index!=0){
                    numero=String.valueOf(jtblFacturas.getValueAt(index, 1));
                    //System.out.println("numero "+numero);
                    cliente=String.valueOf(jtblFacturas.getValueAt(index, 2));
                    dispose();
                //}
                
            }
        });
    }
    public void buscarSecuencial(){
        conexion_mysql cn=new conexion_mysql();
        Connection cc=cn.conectar();
        String sql="";
        sql="select NUM_SEC FROM secuencial";
        try {
            Statement ps=cc.createStatement();
            ResultSet rs=ps.executeQuery(sql);
            while(rs.next()){
                lblSecuencial.setText(rs.getString("NUM_SEC"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(busquedaFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void busqueda(String secuencial){
        String[] datosF=new String[4];
        String[] titulos={"Numeración","Secuencial","Ced. Cliente","Nombres y Apellidos cliente"};
        modelo=new DefaultTableModel(null, titulos);
        conexion_mysql cc=new conexion_mysql();
        Connection cn=cc.conectar();
        String sql="";
        sql="select e.sec_fac,e.num_fac,e.clie_fac,CONCAT_WS(' ',cli.NOM_CLI, cli.NOM_CLI1, cli.ape_cli, cli.ape_cli1) as nombres from clientes cli, encabezadofactura e "
                + "where e.num_fac like '%"+secuencial+"%' and e.clie_fac=cli.CI_CLI";
        //System.out.println(sql);
        try {
            Statement ps=cn.createStatement();
            ResultSet rs=ps.executeQuery(sql);
            while(rs.next()){
                datosF[0]=rs.getString("sec_fac");
                datosF[1]=rs.getString("num_fac");
                datosF[2]=rs.getString("clie_fac");
                datosF[3]=rs.getString("nombres");
                modelo.addRow(datosF);
            }
            jtblFacturas.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(busquedaFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFactura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSecuencial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblFacturas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFacturaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFacturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFacturaKeyTyped(evt);
            }
        });

        jLabel1.setText("Secuencial:");

        jtblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblFacturas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSecuencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacturaKeyPressed
        // TODO add your handling code here:
        busqueda(txtFactura.getText().trim());
    }//GEN-LAST:event_txtFacturaKeyPressed

    private void txtFacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacturaKeyReleased
        // TODO add your handling code here:
        busqueda(txtFactura.getText().trim());
    }//GEN-LAST:event_txtFacturaKeyReleased

    private void txtFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacturaKeyTyped
        // TODO add your handling code here:
        busqueda(txtFactura.getText().trim());
    }//GEN-LAST:event_txtFacturaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(busquedaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(busquedaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(busquedaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(busquedaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                busquedaFactura dialog = new busquedaFactura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblFacturas;
    private javax.swing.JLabel lblSecuencial;
    private javax.swing.JTextField txtFactura;
    // End of variables declaration//GEN-END:variables
}
