/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogs;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sistema.de.facturacion.conexion_mysql;

/**
 *
 * @author Benjita
 */
public class generarCobros extends javax.swing.JDialog {

    /**
     * Creates new form generarCobros
     */
    public generarCobros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblSecuencial.setText("002-001");
        lblNumero.setText("000000002");
        txtTotal.setText("18.20");
        txtTotal.setEnabled(false);
        txtRecibo.requestFocus();
    }

    public generarCobros(java.awt.Frame parent, boolean modal, String secuencial, String numero, String total) {
        super(parent, modal);
        initComponents();
        lblSecuencial.setText(secuencial);
        lblNumero.setText(numero);
        txtTotal.setText(total);
        txtTotal.setEnabled(false);
        txtRecibo.requestFocus();
    }

    public void generar() {
        int ope=0;
        float totat = Float.valueOf(txtTotal.getText().toString());
        float recibo = Float.valueOf(txtRecibo.getText().toString());
        if (totat > recibo) {
            double resultado = totat - recibo;
            resultado = (Math.floor(resultado * 100) / 100.0) + 0.01;
            JOptionPane.showMessageDialog(null, "Falta pagar $= " + resultado);
            ope++;
        } else {
            if (totat == recibo) {
                JOptionPane.showMessageDialog(null, "Factura Cancelada");
                
            } else {
                double resultado = recibo - totat;
                resultado = (Math.floor(resultado * 100) / 100.0) + 0.01;
                JOptionPane.showMessageDialog(null, "Debe dar de vuelto $= " + resultado);
            }
        }
        System.out.println("ope"+ope);
        if(ope==0){
            guardar();
        }
    }

    public void guardar() {
        conexion_mysql cn=new conexion_mysql();
        Connection cc=cn.conectar();
        String sql="";
        sql="insert into cobros(`sec_fac`,`num_fac_p`,`tot_fac`,`abo_cob`) "
                + "values(?,?,?,?)";
        String sec_fac,num_fac_p;
        float tot_fac,abo_cob;
        sec_fac=lblSecuencial.getText().trim();
        num_fac_p=lblNumero.getText().trim();
        tot_fac=Float.valueOf(txtTotal.getText().trim());
        abo_cob=Float.valueOf(txtTotal.getText().trim());
        try {
            PreparedStatement ps=cc.prepareStatement(sql);
            ps.setString(1, sec_fac);
            ps.setString(2, num_fac_p);
            ps.setFloat(3, tot_fac);
            ps.setFloat(4, abo_cob);
            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null, "Cobro Guaradado");
            }
        } catch (SQLException ex) {
            Logger.getLogger(generarCobros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSecuencial = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRecibo = new javax.swing.JTextField();
        jbtnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Factura:");

        jLabel2.setText("Total Pagar");

        jLabel3.setText("Recibo $:");

        jbtnGenerar.setText("Generar Pago");
        jbtnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38)
                                .addComponent(lblSecuencial, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal)
                                    .addComponent(txtRecibo)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jbtnGenerar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSecuencial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jbtnGenerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerarActionPerformed
        // TODO add your handling code here:
        generar();
    }//GEN-LAST:event_jbtnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generarCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generarCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generarCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generarCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                generarCobros dialog = new generarCobros(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnGenerar;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSecuencial;
    private javax.swing.JTextField txtRecibo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
